repos:
  # ⬇ black + isort (очень быстро)
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks: [{id: black}]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks: [{id: isort}]

  # ⬇ ruff (линтер + autofix)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      - id: ruff
        args: [--fix, --exit-zero]
  
  # ⬇ mypy быстрый режим
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--install-types, --non-interactive, "--ignore-missing-imports"]

  # ⬇ pytest smoke (только метка "fast")
  - repo: local
    hooks:
      - id: pytest-fast
        name: "pytest -m fast"
        entry: poetry run pytest -q -m fast
        language: system
        types: [python]
        pass_filenames: false
        stages: [push]      # выполняем на pre-push